#!/usr/bin/env bash

brew update \
  && brew upgrade

brew list --cask > ~/local/homebrew-installed-casks
brew leaves --installed-on-request > ~/local/homebrew-installed
brew tap > ~/local/homebrew-taps

